### ISSUE TITLE
[Table] Image 在 Room Table 中的預設值

### ISSUE THREAD

**Issue by MeteorVE** [cty001996/se_project#12]
## Context

Image 在 Room Table 中的預設值

## Process

提出原因 : 
即使使用者不輸入，前端在讀取 RoomList 時仍然會拿到此預設值
並且 <img> 會嘗試去 /GET (雖然前端有 handle 住但 /GET and wait 的時間仍然在)

## Expected result

'' (空字串即可)，或是 null

## Current result

'http//:123.com'

## Possible Fix

'' (空字串即可)

## Screenshot

none

## Examples

none

**Comment by cty001996** [comment]
已改為空字串
