### ISSUE TITLE
[method] blockList, memberList, roomRecord 相關權限設定

### ISSUE THREAD

**Issue by MeteorVE** [cty001996/se_project#14]
## Context

某使用者不在該房間時，blockList, memberList, roomRecord 都能被看到

## Process

測試方式可以直接拿 token 去 try。
而實際情況，是會把他導回首頁的，故只是 check 一下設定部分

* 其中，blockList 免 token 就能 /GET
* 不過，首頁的 Room-Card 不會顯示該"房間人數"。
  以目前 API 來說，只能每個房間都去 getMemberList 然後計算 length 去顯示。
  (而使用者不可能所有房間都參加) 
  如果開了新 API，那就沒有其他疑慮了。

## Expected result

username filed

## Current result

none

## Possible Fix

調整權限、開新 API (/GET, { roomid, room_current_people_number })

## Screenshot

none

## Examples

none

**Comment by cty001996** [comment]
blacklist and roomRecord 已改成在房內才能看到
memberList 維持大家都能看到
