### ISSUE TITLE
[Method] Moderator 是否能被 Admin 給 Remove / Block

### ISSUE THREAD

**Issue by MeteorVE** [cty001996/se_project#15]
## Context

Moderator 是否能被 Admin 給 Remove/ Block

## Process

將某人提升成房管，然後由 admin 對他進行 remove，
會跑出錯誤訊息 : 他是 moderator 故不能被移除，且 res_status_code 是 401
此 issue 為確認這樣的設定，若是，會提醒使用者，並且後端不用更動 (但 401 會於另一串討論)

## Expected result

remove

## Current result

error message: 他是 moderator 故不能被移除

## Possible Fix

modify logic

## Screenshot

![image](https://user-images.githubusercontent.com/15828515/121087972-ad2ad300-c817-11eb-849a-cd5cdaf7436f.png)

![image](https://user-images.githubusercontent.com/15828515/121088305-1f9bb300-c818-11eb-99e0-70f5397eaa8d.png)

## Examples

none

**Comment by cty001996** [comment]
已改成只有admin不能被移除，manager現在可被移除。status code 已改成403
