### ISSUE TITLE
[Design] 關於 HTTP 狀態碼設計

### ISSUE THREAD

**Issue by MeteorVE** [cty001996/se_project#18]
## Process

在遇到 Admin 踢了 Moderator 時偶然觸發 401 function

但因為前端的設計是參考 401 Unauthorized = ``[帳密錯誤/沒有 token/有 token 但是是非法的]`` 認為只有此三類情況
故會攔截 401 Error 然後強制把使用者的 token 清除。

於是上述的單純 invalid 操作觸發了強制登出，故開始考慮是否不該幫 401 設計此 flow 或是 status code 可以調整。

## Context

呈上，於是去查看相關介紹

> 401 Unauthorized
> 需要授權以回應請求。它有點像 403，但這裡的授權，是有可能辦到的。
> 
> 403 Forbidden
> 用戶端並無訪問權限，例如未被授權，所以伺服器拒絕給予應有的回應。不同於 401，伺服端知道用戶端的身份。
> 
> Source: [HTTP 狀態碼  MDN-Web-Docs](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Status)

## Possible Fix

如果上述文件的解釋是正確的，那 403 的特點就是 "伺服端知道用戶端的身份" (token 是有效的，但他剛好觸動了非法操作)
故如上述的操作也許都該改成 403，
並且在 API Document 內 Search ``401``，每個 API 可能最多只會存在一個 401 (且情形為 Unauthorized 非 Forbidden)

另外補充 400 與 404

> 400 Bad Request
> 此回應意味伺服器因為收到無效語法，而無法理解請求。
> 
> 404 Not Found
> 伺服器找不到請求的資源。因為在網路上它很常出現，這回應碼也許最為人所悉。

不確定在 Design 上面有沒有其他 API 有相關的混淆情形發生，可能得請後端 check。

## Expected result

Give a 403 Forbidden status code.

## Current result

Give a 401 Forbidden status code.

## Screenshot

none

## Examples

none

**Comment by cty001996** [comment]
無權限的操作都已修改成403，只有尚未認證才會返回401
